Add cart tag to get tax split by tax rate.
damcclean/simple-commerce pull request #759
Opened 2022-11-07 18:27 UTC by Sm1lEE

Depending on local rights, the order taxes have to be shown split by tax rate, e. g. 7% -> 4,55€: 19% -> 15,21€. The new tag allows just this, and comes with a variant to get also the raw values.

Also the documentation includes the new tag.

2022-11-07 18:36 UTC, Sm1lEE commented
Here is an example screenshot showing the standard tax and the split tax and split tax raw:
<img width="246" alt="image" src="https://user-images.githubusercontent.com/2184676/200388186-746001f1-32ce-459d-b354-715cd10ef916.png">

2022-11-07 19:34 UTC, duncanmcclean requested changes
Can you add some documentation about how the new tag would be used?

And, if possible, also a test.

2022-11-08 08:10 UTC, Sm1lEE commented
Sure, I will do.

2022-11-08 20:39 UTC, Sm1lEE commented
Hi @duncanmcclean, I've added a test case for the new tag.

The test case is fairly long compared to the other ones, but I did not know how to write the logic for creating tax rates, categories, products, carts... in any other way.

I'm all new to the testing-game, so if something is wrong, please let me know.

2022-11-08 20:49 UTC, duncanmcclean commented
I've had a brief look and it seems good! I'll give this PR a proper review later in the week/at the weekend.

Thanks!

2022-11-12 11:35 UTC, duncanmcclean approved these changes
Looks good - thanks for your contribution! 🙌

2022-11-12 11:35 UTC, merged